### ISSUE TITLE
The release script for the site is broken

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs-site#23]
I think ocadotechnology/hexagonjs-site/pull/21 has broken something in the build process. 

When running

```
npm run release
```

It only builds the site with the latest version. Guessing it is using the new dev mode somewhere it shouldn't be?

**Comment by charlieTheBotDev** [comment]
The issue was that the `meta.json` was being built incorrectly as buildMeta was being passed a promise, an oversight on my behalf.
