### ISSUE TITLE
Extra section in color module is being merged incorrectly

### ISSUE THREAD

**Issue by andersschuller** [ocadotechnology/hexagonjs-site#78]
In the documentation for the color module, each version includes a slightly different version of the "Other functionality and examples" section using `@extra: @inline <version>/extra.um`. Prior to the fixes in #76, this resulted in some of the codeblocks in this section being duplicated because some were plain `@codeblock` and some were `@codeblock js`, which suggests that this extra section is being merged despite the fact that it should not be.

This is currently resulting in some strange behaviour where the example tables in e.g. the "Lightness" section are not being rendered as the specific version being requested. For example:
- in [0.9.0](https://www.hexagonjs.io/docs/0.9.0/color/), the table shows correctly
- in [0.15.2](https://www.hexagonjs.io/docs/0.15.2/color/), the table still contains `exCol.darken(0.2)` despite the fact that the text was changed to `exCol.lighten(-0.2)`, the text in the last column is duplicated, and deprecation warnings are logged to the console
- in [1.0.0](https://www.hexagonjs.io/docs/1.0.0/color/), the table contains the same text as in 0.15.2, but now one of the examples is not displayed and an error is logged to the console

**Comment by charlieTheBotDev** [comment]
Turns out that this was down to the `unmergeable` option being passed in as `unmergable` so the versioning was attempting to merge things which it shouldn't have been doing...
