### ISSUE TITLE
Site includes hexagon twice

### ISSUE THREAD

**Issue by rowan-simms** [ocadotechnology/hexagonjs-site#81]
Site includes both https://www.hexagonjs.io/resources/hexagon/1.1.0/hexagon.js and https://www.hexagonjs.io/resources/hexagon/docs/hexagon.js which is confusing because I don't know which one to put breakpoints in

**Comment by charlieTheBotDev** [comment]
Hexagon 1.1.0 is for the examples, docs/hexagon.js is for building the site. This is so the site can use a version independent of the one used for showing the examples. Anything using `dx` is using `docs/hexagon.js`, everything else uses `{version}/hexagon.js`
